### ISSUE TITLE
Native Android app for PhotoPrism

### ISSUE THREAD

**Issue by Radiokot** [perryizgr8/perryizgr8.github.io#7]
Hi 👋🏻
I've seen your article on Google Photos alternative. There you concluded that PhotoPrism is not a good option for you because it misses a native app. Can't argue on that, the PWA is fully functional but yet it is a laggy webpage :( That's why I've created [a native gallery and content provider for PhotoPrism](https://github.com/Radiokot/photoprism-android-client), which has both essential and some exclusive features.
Maybe it will bring you to the PhotoPrism side? 😁

**Comment by perryizgr8** [comment]
Hey! I just installed your app a few minutes ago. It works great, I can see myself using it from now on. I feel this is what PhotoPrism official app should have been like. Congrats on creating the app and good work!

**Comment by Radiokot** [comment]
Glad to hear! Thanks for checking out :)
